// Mocks generated by Mockito 5.4.5 from annotations
// in testverygood/test/transaction/trans_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:testverygood/data/data_api/add_trans_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionService extends _i1.Mock
    implements _i2.TransactionService {
  MockTransactionService() {
    _i1.throwOnMissingStub(this);
  }
  Future<void> saveTransaction(
      {String? uuid,
      String? selectedCategory,
      String? selectedDate,
      String? money,
      String? note,
      String? toFrom,
      String? imageFile,
      String? type}) {
    return (super.noSuchMethod(
        Invocation.method(#saveTransaction, [
          uuid,
          selectedCategory,
          selectedDate,
          money,
          note,
          toFrom,
          imageFile,
          type
        ]),
        returnValue: Future.value(true)) as Future<bool>);
  }
}
